/** Builtin signatures in compact form: "<elemSet> <params...> -> <ret>", with
 * overloads separated by ";". The element set letters and the parameter tokens
 * are defined in OverloadMatch.ts, which parses and matches these. */
export const signatures: Record<string, string> = {
  // logical
  all: "b T -> bool",
  any: "b T -> bool",
  select: "a T T bool -> T; a V V B -> V",

  // numeric, component-wise unless noted
  abs: "n T -> T",
  acos: "f T -> T",
  acosh: "f T -> T",
  asin: "f T -> T",
  asinh: "f T -> T",
  atan: "f T -> T",
  atanh: "f T -> T",
  atan2: "f T T -> T",
  ceil: "f T -> T",
  clamp: "n T T T -> T",
  cos: "f T -> T",
  cosh: "f T -> T",
  cross: "f V3 V3 -> V3",
  degrees: "f T -> T",
  distance: "f T T -> E",
  dot: "n V V -> E",
  dot4U8Packed: "- u32 u32 -> u32",
  dot4I8Packed: "- u32 u32 -> i32",
  exp: "f T -> T",
  exp2: "f T -> T",
  faceForward: "f V V V -> V",
  floor: "f T -> T",
  fma: "f T T T -> T",
  fract: "f T -> T",
  inverseSqrt: "f T -> T",
  ldexp: "f T Ti -> T",
  length: "f T -> E",
  log: "f T -> T",
  log2: "f T -> T",
  max: "n T T -> T",
  min: "n T T -> T",
  mix: "f T T T -> T; f V V E -> V",
  normalize: "f V -> V",
  pow: "f T T -> T",
  quantizeToF16: "F T -> T",
  radians: "f T -> T",
  reflect: "f V V -> V",
  refract: "f V V E -> V",
  round: "f T -> T",
  saturate: "f T -> T",
  sign: "s T -> T",
  sin: "f T -> T",
  sinh: "f T -> T",
  smoothstep: "f T T T -> T",
  sqrt: "f T -> T",
  step: "f T T -> T",
  tan: "f T -> T",
  tanh: "f T -> T",
  trunc: "f T -> T",

  // integer bit functions
  countLeadingZeros: "I T -> T",
  countOneBits: "I T -> T",
  countTrailingZeros: "I T -> T",
  extractBits: "I T u32 u32 -> T",
  firstLeadingBit: "I T -> T",
  firstTrailingBit: "I T -> T",
  insertBits: "I T T u32 u32 -> T",
  reverseBits: "I T -> T",

  // derivatives (fragment stage, f32 only)
  dpdx: "F T -> T",
  dpdxCoarse: "F T -> T",
  dpdxFine: "F T -> T",
  dpdy: "F T -> T",
  dpdyCoarse: "F T -> T",
  dpdyFine: "F T -> T",
  fwidth: "F T -> T",
  fwidthCoarse: "F T -> T",
  fwidthFine: "F T -> T",

  // data packing
  pack4x8snorm: "- vec4f -> u32",
  pack4x8unorm: "- vec4f -> u32",
  pack4xI8: "- vec4i -> u32",
  pack4xU8: "- vec4u -> u32",
  pack4xI8Clamp: "- vec4i -> u32",
  pack4xU8Clamp: "- vec4u -> u32",
  pack2x16snorm: "- vec2f -> u32",
  pack2x16unorm: "- vec2f -> u32",
  pack2x16float: "- vec2f -> u32",
  unpack4x8snorm: "- u32 -> vec4f",
  unpack4x8unorm: "- u32 -> vec4f",
  unpack4xI8: "- u32 -> vec4i",
  unpack4xU8: "- u32 -> vec4u",
  unpack2x16snorm: "- u32 -> vec2f",
  unpack2x16unorm: "- u32 -> vec2f",
  unpack2x16float: "- u32 -> vec2f",

  // synchronization (textureBarrier lives in TextureSignatures.ts: the
  // texture* name dispatch reaches textureFnType before this table)
  storageBarrier: "- -> void",
  workgroupBarrier: "- -> void",

  // subgroup and quad operations: concrete element sets (N, I), because these
  // aren't const-evaluable and so have no abstract overloads in the spec.
  // An abstract argument materializes instead: subgroupAdd(1) is i32.
  subgroupAdd: "N T -> T",
  subgroupExclusiveAdd: "N T -> T",
  subgroupInclusiveAdd: "N T -> T",
  subgroupMul: "N T -> T",
  subgroupExclusiveMul: "N T -> T",
  subgroupInclusiveMul: "N T -> T",
  subgroupMax: "N T -> T",
  subgroupMin: "N T -> T",
  subgroupAnd: "I T -> T",
  subgroupOr: "I T -> T",
  subgroupXor: "I T -> T",
  subgroupAll: "b bool -> bool",
  subgroupAny: "b bool -> bool",
  subgroupBallot: "b bool -> vec4u",
  subgroupElect: "b -> bool",
  subgroupBroadcast: "N T X -> T",
  subgroupBroadcastFirst: "N T -> T",
  subgroupShuffle: "N T X -> T",
  subgroupShuffleUp: "N T X -> T",
  subgroupShuffleDown: "N T X -> T",
  subgroupShuffleXor: "N T X -> T",
  quadBroadcast: "N T X -> T",
  quadSwapDiagonal: "N T -> T",
  quadSwapX: "N T -> T",
  quadSwapY: "N T -> T",
};
