import type { ModuleResolver } from "./ModuleResolver.ts";
import { parseSrcModule, type WeslAST } from "./ParseWESL.ts";
import type { Conditions } from "./Scope.ts";

/** Context passed to virtual library generators. */
export interface VirtualLibContext {
  conditions: Conditions;
  rootModulePath: string;
  packageName: string;
}

/** Generate a virtual WESL module. */
export type VirtualLibraryFn = (ctx: VirtualLibContext) => string;

/** Create a resolver for runtime generated modules.
 *
 * The context is the generators' only view of the link, so it's required:
 * a defaulted rootModulePath would silently point generated imports
 * (`import ${ctx.rootModulePath}::Foo`) at the wrong module.
 *
 * Returns undefined when no libraries are given, so the result composes
 * cleanly with composeResolvers (which skips undefined entries). */
export function createVirtualLibraryResolver(
  virtualLibs: Record<string, VirtualLibraryFn>,
  ctx: VirtualLibContext,
): VirtualLibraryResolver | undefined {
  if (Object.keys(virtualLibs).length === 0) return undefined;
  return new VirtualLibraryResolver(virtualLibs, ctx);
}

/** Resolver for virtual libraries: modules generated by host code at runtime
 * (e.g. `env::` for test uniforms).
 *
 * Generated ASTs are cached for the life of the resolver. Generators see the
 * context (including conditions) at construction time, so create a new
 * resolver to link with different conditions. */
export class VirtualLibraryResolver implements ModuleResolver {
  private readonly astCache = new Map<string, WeslAST>();
  readonly libs: Record<string, VirtualLibraryFn>;
  readonly ctx: VirtualLibContext;

  constructor(libs: Record<string, VirtualLibraryFn>, ctx: VirtualLibContext) {
    this.libs = libs;
    this.ctx = ctx;
  }

  resolveModule(modulePath: string): WeslAST | undefined {
    const cached = this.astCache.get(modulePath);
    if (cached) return cached;

    const fn = this.libs[modulePath];
    if (!fn) return undefined;

    // parse under the host package so that package:: references
    // in generated code resolve to host modules
    const ast = parseSrcModule({
      modulePath: `${this.ctx.packageName}::${modulePath}`,
      debugFilePath: modulePath,
      src: fn(this.ctx),
    });
    this.astCache.set(modulePath, ast);
    return ast;
  }
}
